### ISSUE TITLE
GAP012 | Lote Com R na geração da OP

### ISSUE THREAD

**Issue by evandromarianodux** [DuxNutrition/Protheus#13]
**GAP012 | Lote Com R na geração da OP**

**Objetivo:** Incluir no final do Lote o R, na abertura da OP;
**Especificação Técnica:** Não Há
**Manual Técnico:**  [GAP012 - Manual Técnico.pdf](https://github.com/user-attachments/files/16443028/GAP012.-.Manual.Tecnico.pdf)
**Termo de Entrega:**  https://app.lexio.legal/empresa/contrato/728257

**Comment by allandux** [comment]
[GAP012 - Manual Técnico.pdf](https://github.com/user-attachments/files/16443028/GAP012.-.Manual.Tecnico.pdf)


[GAP012 - Termo de Entrega.pdf](https://github.com/user-attachments/files/16443029/GAP012.-.Termo.de.Entrega.pdf)
